version: "3.9"
services:
  mysql:
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=root
    hostname: mysql
    command:
      - --table_definition_cache=100
      - --performance_schema=0
      - --default-authentication-plugin=mysql_native_password
      - --innodb_use_native_aio=0
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./storage/mysql:/var/lib/mysql
    container_name: mysql
    ports:
      - 3306:3306
    image: mysql
    restart: always
  grafana:
    container_name: grafana
    image: grafana/grafana:7.5.3
    volumes:
      - ./storage/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - api
      - mysql
  api:
    container_name: api
    image: python:3.9.4
    volumes:
      - ./api/api.py:/api.py
      - ./api/requirements.txt:/requirements.txt
      - ./api/entrypoint.sh:/entrypoint.sh
    ports:
      - 5000:5000
    restart: always
    entrypoint: /entrypoint.sh
    depends_on:
      - mysql
volumes:
  databases: {}